In [114]:
import pandas as pd
merge_ko_en_1 = pd.DataFrame()

In [115]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [116]:
import numpy as np
from pandas import DataFrame
from sklearn.model_selection import train_test_split

#구어체
A1 = pd.read_excel("/content/drive/MyDrive/groom_project3/1_구어체(1).xlsx")
B1 = pd.read_excel("/content/drive/MyDrive/groom_project3/1_구어체(2).xlsx")
C1 = pd.read_excel("/content/drive/MyDrive/groom_project3/2_대화체.xlsx")

/usr/local/lib/python3.8/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [117]:
A1_train, A1_test = train_test_split(A1, test_size=0.2, random_state=42)
A1_train, A1_val = train_test_split(A1_train, test_size=0.125, random_state=42)

B1_train, B1_test = train_test_split(B1, test_size=0.2, random_state=42)
B1_train, B1_val = train_test_split(B1_train, test_size=0.125, random_state=42)

C1_train, C1_test = train_test_split(C1, test_size=0.2, random_state=42)
C1_train, C1_val = train_test_split(C1_train, test_size=0.125, random_state=42)

print("구어체1 train, 구어체1 val, 구어체1 test", len(A1_train), len(A1_val), len(A1_test))
print("구어체2 train, 구어체2 val, 구어체2 test", len(B1_train), len(B1_val), len(B1_test))
print("대화체 train, 대화체2 val, 대화체2 test", len(C1_train), len(C1_val), len(C1_test))
print(" ")
print("구어체1", len(A1_train) + len(A1_val) + len(A1_test))
print("구어체2", len(B1_train) + len(B1_val) + len(B1_test))
print("대화체", len(C1_train) + len(C1_val) + len(C1_test))
print(" ")
print("train", len(A1_train) + len(B1_train) + len(C1_train))
print("val", len(A1_val) + len(B1_val) + len(C1_val))
print("test", len(A1_test) + len(B1_test) + len(C1_test))

구어체1 train, 구어체1 val, 구어체1 test 140000 20000 40000
구어체2 train, 구어체2 val, 구어체2 test 140000 20000 40000
대화체 train, 대화체2 val, 대화체2 test 70000 10000 20000

구어체1 200000
구어체2 200000
대화체 100000

train 350000
val 50000
test 100000

In [118]:
columns = ['원문', '번역문']

train_merge_df = pd.DataFrame()
val_merge_df = pd.DataFrame()
test_merge_df = pd.DataFrame()

A1_train_df = pd.DataFrame(A1_train, columns=columns)
B1_train_df = pd.DataFrame(B1_train, columns=columns)
C1_train_df = pd.DataFrame(C1_train, columns=columns)

A1_val_df = pd.DataFrame(A1_val, columns=columns)
B1_val_df = pd.DataFrame(B1_val, columns=columns)
C1_val_df = pd.DataFrame(C1_val, columns=columns)

A1_test_df = pd.DataFrame(A1_test, columns=columns)
B1_test_df = pd.DataFrame(B1_test, columns=columns)
C1_test_df = pd.DataFrame(C1_test, columns=columns)

train_merge_df = train_merge_df.append(A1_train_df, ignore_index=False)
train_merge_df = train_merge_df.append(B1_train_df, ignore_index=False)
train_merge_df = train_merge_df.append(C1_train_df, ignore_index=False)

val_merge_df = val_merge_df.append(A1_val_df, ignore_index=False)
val_merge_df = val_merge_df.append(B1_val_df, ignore_index=False)
val_merge_df = val_merge_df.append(C1_val_df, ignore_index=False)

test_merge_df = test_merge_df.append(A1_test_df, ignore_index=False)
test_merge_df = test_merge_df.append(B1_test_df, ignore_index=False)
test_merge_df = test_merge_df.append(C1_test_df, ignore_index=False)

train_merge_df.to_csv("구어체_train.csv", index=False, encoding = "utf-8-sig")

val_merge_df.to_csv("구어체_val.csv", index=False, encoding = "utf-8-sig")

test_merge_df.to_csv("구어체_test.csv", index=False, encoding = "utf-8-sig")

In [119]:
df = pd.read_csv("/content/구어체_train.csv")
print(len(df))
df = df.head(10)
df

350000

,원문,번역문
0,나는 비록 영어가 서투르지만 당신에 대해 알고 싶고 얘기하고 싶어요.,"Although I am not good at English, I would lik..."
1,"심청은 행복한 나날을 보내지만, 아버지가 자꾸 생각납니다.","Even though Shim Chung has happy days, she can..."
2,사우나 시설은 라운딩을 한 선수들만 이용 가능한가요?,"Are the sauna facilities off-limits to anyone,..."
3,내가 작년에 내 친구에게 내 카드와 통장을 빌려주지 않았다면 내가 이렇게 힘들지도 ...,I wouldn't gone through this hard time if I ha...
4,"사상 최대 규모인 92개국 2,900여명의 선수들이 참가한 평창 올림픽은 인류의 화...",The Pyeongchang Winter Olympics held as the la...
5,이 가격은 조금 전에 내가 보았던 거와 다른데.,The price is different from what I just saw.
6,그 특징들은 마땅히 존중 받아야 해요.,Those features should be respected.
7,이용당한 느낌이 들어서 난 더 당신 회사를 이용하지 않을 것입니다.,I will no longer be patronizing your company s...
8,이번 주 수요일에 회의하는 건 어때?,What about having a meeting this Wednesday?
9,네 홈페이지 주소록에 등록이 가능해?.,Is it possible to register in the address list...

In [120]:
df = pd.read_csv("/content/구어체_val.csv")
print(len(df))
df = df.head(10)
df

50000

,원문,번역문
0,"일본 요리는 맛도 좋지만, 모양도 참 예뻐요.",Japanese dishes are very fancy not only in tas...
1,10월 초에 스케줄이 괜찮을 것 같긴 해요.,My schedule seems to be available in early Oct...
2,나는 컨디션이 좋을 때 그것을 하루에 3~4번 합니다.,"When my condition is good, I do it 34times a day."
3,손가락을 마주 잡고 문지릅니다.,Hold fingers together and rub them.
4,우리는 공동체 의식을 지니고 살아야 합니다.,We need to live with a community spirit.
5,내가 요새 정신이 없어서 답장을 지금 보내.,I was so busy that I am replying right now.
6,당신은 이 술집에 꽤 자주 오네요.,You come to this bar quite often.
7,그는 후에 도움이 될만한 사람과 만날지도 몰라요.,He may find someone who helps him out later.
8,음식도 맛있고 사람들도 다 친절해요.,"The food is great, and people are kind."
9,나는 전시회에 참가하기 위해 15일 전에 너에게 이메일을 보냈어.,I sent an email to you 15 days ago to attend t...

In [121]:
df = pd.read_csv("/content/구어체_test.csv")
print(len(df))
df = df.head(10)
df

100000

,원문,번역문
0,사과는 잘 씻은 뒤 껍질 채 먹는 게 좋다네요.,It's healthier to eat the apple with its skin ...
1,내가 언제까지 거기 가면 됩니까?,Untill when should I be there?
2,우리가 작성해서 전달해 드려야 하나요?,Do we have to write and transmit it?
3,"난 지금 행복해요, 세상이 나를 원하고 있죠.","I’m happy now, this world wants me."
4,그는 틀림없이 꽃 가게에 들렸을 겁니다.,He must have dropped by a flower shop.
5,"그녀가 좋아하는 가수는 박효신인데, 나는 그녀가 그와 같은 멋진 남자친구가 생기길 ...","The singer she likes is Hyosin Park, but I hop..."
6,안녕하세요 올해가 돼서 매우 기쁘고요. 행복한 올해가 되세요!,"Hello, I'm really glad its this year now, have..."
7,이 호텔은 세계 최악의 호텔로 유명합니다.,The hotel is infamous for the worst hotel in t...
8,"아래 그림의 bga 부분에 대해서는, nsmd에서 smd로 존재하는 것과 같은 방식...","About the bga part of the picture below, we wi..."
9,500달러만 당신들에게 요청할게요.,We ask you to pay only $500.

In [122]:
#문어체

In [123]:
news1 = pd.read_excel("/content/drive/MyDrive/groom_project3/3_문어체_뉴스(1)_200226.xlsx")
news2 = pd.read_excel("/content/drive/MyDrive/groom_project3/3_문어체_뉴스(2).xlsx")
news3 = pd.read_excel("/content/drive/MyDrive/groom_project3/3_문어체_뉴스(3).xlsx")
news4 = pd.read_excel("/content/drive/MyDrive/groom_project3/3_문어체_뉴스(4).xlsx")
culture = pd.read_excel("/content/drive/MyDrive/groom_project3/4_문어체_한국문화.xlsx")
law = pd.read_excel("/content/drive/MyDrive/groom_project3/5_문어체_조례.xlsx")
web = pd.read_excel("/content/drive/MyDrive/groom_project3/6_문어체_지자체웹사이트.xlsx")

/usr/local/lib/python3.8/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [124]:
news1_cut = pd.DataFrame.sample(news1, n = 25000, replace=False, random_state = 42)
news1_train, news1_val = train_test_split(news1_cut, test_size=0.125, random_state=42)

news2_cut = pd.DataFrame.sample(news2, n = 25000, replace=False, random_state = 42)
news2_train, news2_val = train_test_split(news2_cut, test_size=0.125, random_state=42)

news3_cut = pd.DataFrame.sample(news3, n = 25000, replace=False, random_state = 42)
news3_train, news3_val = train_test_split(news3_cut, test_size=0.125, random_state=42)

news4_cut = pd.DataFrame.sample(news4, n = 25000, replace=False, random_state = 42)
news4_train, news4_val = train_test_split(news4_cut, test_size=0.125, random_state=42)

culture_cut = pd.DataFrame.sample(culture, n = 100000, replace=False, random_state = 42)
culture_train, culture_val = train_test_split(culture_cut, test_size=0.125, random_state=42)

law_cut = pd.DataFrame.sample(law, n = 100000, replace=False, random_state = 42)
law_train, law_val = train_test_split(law_cut, test_size=0.125, random_state=42)

web_cut = pd.DataFrame.sample(web, n = 100000, replace=False, random_state = 42)
web_train, web_val = train_test_split(web_cut, test_size=0.125, random_state=42)

print("뉴스1 train, 뉴스1 val", len(news1_train), len(news1_val))
print("뉴스2 train, 뉴스2 val", len(news2_train), len(news2_val))
print("뉴스3 train, 뉴스3 val", len(news3_train), len(news3_val))
print("뉴스4 train, 뉴스4 val", len(news4_train), len(news4_val))

print("문화 train, 문화 val", len(culture_train), len(culture_val))
print("법률 train, 법률 val", len(law_train), len(law_val))
print("웹사이트 train, 웹사이트 val", len(web_train), len(web_val))

print(" ")
print("train", len(news1_train) + len(news2_train) + len(news3_train) + len(news4_train) + len(culture_train) + len(law_train) + len(web_train))
print("val", len(news1_val) + len(news2_val) + len(news3_val) + len(news4_val) + len(culture_val) + len(law_val) + len(web_val))

뉴스1 train, 뉴스1 val 21875 3125
뉴스2 train, 뉴스2 val 21875 3125
뉴스3 train, 뉴스3 val 21875 3125
뉴스4 train, 뉴스4 val 21875 3125
문화 train, 문화 val 87500 12500
법률 train, 법률 val 87500 12500
웹사이트 train, 웹사이트 val 87500 12500

train 350000
val 50000

In [125]:
columns = ['원문', '번역문']

train_merge2_df = pd.DataFrame()
val_merge2_df = pd.DataFrame()

news1_train_df = pd.DataFrame(news1_train, columns=columns)
news2_train_df = pd.DataFrame(news2_train, columns=columns)
news3_train_df = pd.DataFrame(news3_train, columns=columns)
news4_train_df = pd.DataFrame(news4_train, columns=columns)
culture_train_df = pd.DataFrame(culture_train, columns=columns)
law_train_df = pd.DataFrame(law_train, columns=columns)
web_train_df = pd.DataFrame(web_train, columns=columns)

news1_val_df = pd.DataFrame(news1_val, columns=columns)
news2_val_df = pd.DataFrame(news2_val, columns=columns)
news3_val_df = pd.DataFrame(news3_val, columns=columns)
news4_val_df = pd.DataFrame(news4_val, columns=columns)
culture_val_df = pd.DataFrame(culture_val, columns=columns)
law_val_df = pd.DataFrame(law_val, columns=columns)
web_val_df = pd.DataFrame(web_val, columns=columns)

train_merge2_df = train_merge2_df.append(news1_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(news2_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(news3_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(news4_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(culture_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(law_train_df, ignore_index=False)
train_merge2_df = train_merge2_df.append(web_train_df, ignore_index=False)

val_merge2_df = val_merge2_df.append(news1_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(news2_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(news3_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(news4_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(culture_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(law_val_df, ignore_index=False)
val_merge2_df = val_merge2_df.append(web_val_df, ignore_index=False)


train_merge2_df.to_csv("문어체_train.csv", index=False, encoding = "utf-8-sig")

val_merge2_df.to_csv("문어체_val.csv", index=False, encoding = "utf-8-sig")

In [126]:
df = pd.read_csv("/content/문어체_train.csv")
print(len(df))
df = df.head(10)
df

350000

,원문,번역문
0,참가 학생 모두 그날 배운 것을 그날 완전히 소화하기 위해서는 무엇보다 눈 맞춤 수...,Eye-tailored classes are most important for al...
1,그가 강조하는 생태담론이 과연 발전 단계와 상황이 다른 남반구와 북반구 모두에 보편...,I wonder if he thinks the discussions on ecolo...
2,김민재는 동료들이 자신의 공백을 잘 메우며 2대 0으로 승리한 뒤 “관중석에서 보고...,"Kim Min-jae said he was ""very sorry"" to see hi..."
3,보험 업계에서는 신한생명 사장 내정자인 정문국 오렌지라이프 사장이 1959년생이다.,"In the insurance industry, Jung Moon-guk, the ..."
4,경찰 소관부처인 행정안전부가 시민단체 ‘언론소비자주권행동’이 진영 장관 앞으로 보내...,The move came after the Ministry of the Interi...
5,한류 자체가 창출하는 부가가치는 결코 크지 않다.,The added value created by the Korean Wave its...
6,김기동 목사를 에워싼 경호원들과 신도들은 우산으로 김기동 목사 얼굴을 가리고 김기동...,The guards and believers who surrounded Pastor...
7,"김광현의 뒤를 이어 7회부터 등장한 SK 불펜의 필승조 서진용과 김태훈, 하재훈이 ...","Following Kim Kwang-hyun, SK Bullpen's determi..."
8,지난 12일 오후 7시께 경남 김해시 생림면 한 밭에서 A(85·여)씨가 숨진 채 ...,"The neighbors discovered that A (85 years old,..."
9,"김용찬 행정부지사는 “해삼은 김, 바지락, 굴과 함께 충남의 4대 명품 수산물”이라...","Kim Yong-chan, Deputy Chief of Administration ..."

In [127]:
df = pd.read_csv("/content/문어체_val.csv")
print(len(df))
df = df.head(10)
df

50000

,원문,번역문
0,경찰은 김씨가 난동을 부린 5시간 전 혈중 알코올 농도는 면허 취소 수준인 0.1%...,Police estimate that Kim's blood-alcohol level...
1,반면 몇 년째 LH청년전세임대주택 거래를 해온 한 부동산 중개업자는 전세 지원금 인...,"On the other hand, a real estate agent who has..."
2,이는 이벤트 진행에 따라 접속이 몰리면서 마비된 것으로 보인다.,This seems to be overloaded as the connection ...
3,푸어타이당은 이념이 비슷한 퓨처포워드당과 연립정부를 구성해도 차기 총리를 선출하는 ...,Even if the Pheu Thai Party formed a Future Fo...
4,남·북·일이 3자 축을 만드는 것은 매우 합리적이고 이성적인 방법인데 현실적으로 일...,It is a very reasonable and rational way for t...
5,극중 하재이 역을 맡은 서예지는 태실장(김병희 분)과 함께 봉상필 변호사(이준기 분...,"Seo Ye-ji, who plays Ha Jae-yi in the drama, p..."
6,해외건설협회의 해외건설종합정보서비스에 따르면 올 들어 해외건설 누적 수주액이 전년 ...,According to the Overseas Construction General...
7,김정은 국무위원장은 ‘비핵화 의지가 있느냐’는 질문에 “없었다면 내가 여기까지 왔겠...,"Asked if he had a ""will to denuclearize,"" Chai..."
8,남북이 분단되기 전에도 북위 38도선 이남에 본점을 두고 있는 은행들의 이북 영업소...,"Even before the division of the two Koreas, 65..."
9,"최근 경기 둔화, 정부의 정책 지원 등 변수를 고려하지 않아 ‘효과’가 과장됐다는 ...","Critics argue that the ""effectiveness"" has bee..."